name: conda-poirot-3.10
channels:
    - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - h5py
  - tqdm
  - statsmodels
  - neurodsp
  - netcdf4
  - pytables
  - xarray
  - h5netcdf
  - scikit-learn
  - ipykernel
  - spyder
  - flit
  - python-dotenv
  - mne>=1.3
  - pip:
    - jupyter_ai
    - git+https://github.com/fooof-tools/fooof.git
    - git+https://github.com/danieltomasz/python-ggseg.git
    - git+https://github.com/pyxnat/pyxnat.git@bbrc

