name: conda-poirot-3.10
channels:
    - conda-forge
    - bioconda
dependencies:
  - python=3.10.12
  - blas=*=accelerate
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - h5py
  - tqdm
  - statsmodels
  - neurodsp
  - netcdf4
  - pytables
  - xarray
  - h5netcdf
  - scikit-learn
  - ipykernel
  - spyder
  - spyder-notebook
  - flit
  - python-dotenv
  - mne>=1.4
  - pip
  - snakemake
  - pip:
    - git+https://github.com/fooof-tools/fooof.git
    - git+https://github.com/danieltomasz/python-ggseg.git
    - git+https://github.com/pyxnat/pyxnat.git@bbrc
    - jupyter_ai


